import { PageHead } from "@/components/page-head";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";

const money=(n:number)=>new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0}).format(n);
const localDate=(date:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);
type Row={consignor_name:string;commission_percent:number;sold_units:number;return_units:number;net_sales:number;store_commission:number;consignor_payable:number};
export default async function ConsignmentsPage({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
  const raw=await searchParams;const today=localDate(new Date());const from=/^\d{4}-\d{2}-\d{2}$/.test(raw.from||"")?raw.from!:today.slice(0,8)+"01";const to=/^\d{4}-\d{2}-\d{2}$/.test(raw.to||"")?raw.to!:today;
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();const{data:member}=await supabase.from("store_members").select("store_id,role").eq("user_id",user!.id).eq("active",true).single();
  if(!member||!["owner","manager"].includes(member.role))redirect("/overview");
  const start=new Date(`${from}T00:00:00+08:00`).toISOString();const endDate=new Date(`${to}T00:00:00+08:00`);endDate.setUTCDate(endDate.getUTCDate()+1);
  const{data,error}=await supabase.rpc("get_consignment_report",{p_store_id:member!.store_id,p_from:start,p_to:endDate.toISOString()});const report=data as{rows?:Row[]}|null;const rows=report?.rows||[];
  return <><PageHead title="寄賣拆帳" description="依銷售與單項退貨計算寄賣人應收與門市抽成"/>{error&&<div className="notice page-notice">寄賣報表讀取失敗：{error.message}</div>}<section className="panel report-filter"><form className="report-date-form"><div className="field"><label>開始日期</label><input name="from" type="date" defaultValue={from}/></div><div className="field"><label>結束日期</label><input name="to" type="date" defaultValue={to}/></div><button className="btn primary">套用日期</button></form></section><section className="cards"><div className="metric"><div className="metric-label">寄賣淨銷售</div><div className="metric-value">{money(rows.reduce((n,row)=>n+Number(row.net_sales),0))}</div></div><div className="metric"><div className="metric-label">應付寄賣人</div><div className="metric-value">{money(rows.reduce((n,row)=>n+Number(row.consignor_payable),0))}</div></div><div className="metric"><div className="metric-label">門市抽成</div><div className="metric-value">{money(rows.reduce((n,row)=>n+Number(row.store_commission),0))}</div></div></section><section className="panel"><div className="table-wrap"><table><thead><tr><th>寄賣人／廠商</th><th className="num">抽成％</th><th className="num">售出／退回</th><th className="num">淨銷售</th><th className="num">門市抽成</th><th className="num">應付寄賣人</th></tr></thead><tbody>{!rows.length?<tr><td colSpan={6} className="empty">此期間沒有寄賣銷售資料</td></tr>:rows.map(row=><tr key={`${row.consignor_name}-${row.commission_percent}`}><td><b>{row.consignor_name}</b></td><td className="num">{Number(row.commission_percent).toFixed(1)}%</td><td className="num">{row.sold_units}／{row.return_units}</td><td className="num">{money(Number(row.net_sales))}</td><td className="num">{money(Number(row.store_commission))}</td><td className="num"><b>{money(Number(row.consignor_payable))}</b></td></tr>)}</tbody></table></div></section></>;
}
