"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { z } from "zod";import { createClient } from "@/lib/supabase/server";
const adjustmentSchema=z.object({variantId:z.string().uuid("請選擇商品"),mode:z.enum(["set","increase","decrease"]),quantity:z.coerce.number().int().min(0,"數量不可小於 0"),note:z.string().trim().min(2,"請填寫至少 2 個字的調整原因").max(100)});
const countSchema=z.object({items:z.array(z.object({variant_id:z.string().uuid(),count:z.number().int().min(0)})).min(1,"請至少掃描一項商品"),note:z.string().trim().min(2).max(100)});
function fail(message:string):never{redirect("/inventory?message="+encodeURIComponent(message))}
async function client(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");return supabase}
function refresh(){revalidatePath("/inventory");revalidatePath("/products");revalidatePath("/sales");revalidatePath("/overview")}
export async function adjustInventory(formData:FormData){let input:z.infer<typeof adjustmentSchema>;try{input=adjustmentSchema.parse({variantId:formData.get("variantId"),mode:formData.get("mode"),quantity:formData.get("quantity"),note:formData.get("note")})}catch(e){if(e instanceof z.ZodError)fail(e.issues[0]?.message||"庫存調整資料錯誤");fail("庫存調整資料錯誤")}const supabase=await client();const{data,error}=await supabase.rpc("adjust_inventory",{p_variant_id:input.variantId,p_mode:input.mode,p_quantity:input.quantity,p_note:input.note});if(error)fail("庫存調整失敗："+error.message);refresh();const result=data as {before?:number;change?:number;after?:number}|null;redirect(`/inventory?message=${encodeURIComponent(result?.change===0?"庫存數量沒有變化":`庫存調整完成：${result?.before??"—"} → ${result?.after??"—"}`)}`)}
export async function completeInventoryCount(formData:FormData){let input:z.infer<typeof countSchema>;try{input=countSchema.parse({items:JSON.parse(String(formData.get("items")||"[]")),note:String(formData.get("note")||"掃碼盤點")})}catch(e){if(e instanceof z.ZodError)fail(e.issues[0]?.message||"盤點資料錯誤");fail("盤點資料錯誤")}const supabase=await client();const{data,error}=await supabase.rpc("complete_inventory_count",{p_items:input.items,p_note:input.note});if(error)fail("盤點送出失敗："+error.message);refresh();const result=data as {checked?:number;changed?:number}|null;redirect(`/inventory?message=${encodeURIComponent(`盤點完成：核對 ${result?.checked??input.items.length} 項，調整 ${result?.changed??0} 項`)}`)}
