"use client";

import { useMemo, useState } from "react";
import { adjustPoints, deleteMember, saveMember } from "@/app/(dashboard)/members/actions";

export type MemberRow = { id: string; name: string; phone: string; email: string; points: number; createdAt: string };
export type PointEntry = { id: string; customerId: string; memberName: string; points: number; balanceAfter: number; type: string; note: string; createdAt: string };

export function MemberManager({ rows, history, message, canAdjust, spendAmount, pointValue, enabled }: { rows: MemberRow[]; history: PointEntry[]; message?: string; canAdjust: boolean; spendAmount: number; pointValue: number; enabled: boolean }) {
  const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<MemberRow | "new" | null>(null);
  const [pointMember, setPointMember] = useState<MemberRow | null>(null);
  const filtered = useMemo(() => rows.filter((row) => `${row.name} ${row.phone} ${row.email}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const typeLabel: Record<string, string> = { earn: "消費累積", redeem: "消費折抵", adjustment: "人工調整" };
  return <>
    {message && <div className="notice page-notice" role="status">{message}</div>}
    <div className="page-head"><div><h2>會員管理</h2><p>{enabled ? `每消費 ${spendAmount} 元累積 1 點；1 點可折抵 ${pointValue} 元。` : "目前已暫停會員點數功能。"}</p></div><div className="actions"><button className="btn primary" onClick={() => setEditing("new")}>＋ 新增會員</button></div></div>
    <section className="cards member-summary"><div className="metric"><div className="metric-label">會員人數</div><div className="metric-value">{rows.length}</div></div><div className="metric"><div className="metric-label">流通點數</div><div className="metric-value">{rows.reduce((n, row) => n + row.points, 0)}</div></div><div className="metric"><div className="metric-label">本次規則</div><div className="member-rule">{spendAmount} 元 = 1 點<br/><small>1 點折 {pointValue} 元</small></div></div></section>
    <section className="panel"><div className="toolbar"><input className="input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋姓名、電話或 Email…"/><span className="hint">共 {filtered.length} 位</span></div><div className="table-wrap"><table><thead><tr><th>會員</th><th>聯絡方式</th><th className="num">可用點數</th><th>加入日期</th><th>操作</th></tr></thead><tbody>{filtered.length === 0 ? <tr><td colSpan={5} className="empty">尚無會員，按「新增會員」建立第一位會員。</td></tr> : filtered.map((row) => <tr key={row.id}><td><b>{row.name}</b></td><td>{row.phone || "—"}<br/><small>{row.email || ""}</small></td><td className="num"><span className="points-badge">{row.points} 點</span></td><td>{row.createdAt}</td><td><div className="row-buttons"><button className="btn sm" onClick={() => setEditing(row)}>編輯</button>{canAdjust && <button className="btn sm" onClick={() => setPointMember(row)}>調整點數</button>}{canAdjust && <form action={deleteMember} onSubmit={(event) => { if (!confirm(`確定刪除會員「${row.name}」？`)) event.preventDefault(); }}><input type="hidden" name="id" value={row.id}/><button className="btn sm danger">刪除</button></form>}</div></td></tr>)}</tbody></table></div></section>
    <section className="panel"><div className="panel-head"><div><h3>最近點數紀錄</h3><p>所有累積、折抵與人工調整都會留下流水帳</p></div></div><div className="table-wrap"><table><thead><tr><th>時間</th><th>會員</th><th>類型</th><th className="num">變動</th><th className="num">結餘</th><th>原因</th></tr></thead><tbody>{history.length === 0 ? <tr><td colSpan={6} className="empty">尚無點數紀錄</td></tr> : history.map((entry) => <tr key={entry.id}><td>{entry.createdAt}</td><td>{entry.memberName}</td><td><span className="pill">{typeLabel[entry.type] || entry.type}</span></td><td className={`num ${entry.points < 0 ? "negative" : "positive"}`}>{entry.points > 0 ? "+" : ""}{entry.points}</td><td className="num">{entry.balanceAfter}</td><td>{entry.note || "—"}</td></tr>)}</tbody></table></div></section>
    {editing && <div className="modal-backdrop"><section className="modal-card member-modal" role="dialog" aria-modal="true"><div className="panel-head"><div><h3>{editing === "new" ? "新增會員" : "編輯會員"}</h3><p>電話可用於結帳時快速搜尋會員。</p></div><button className="btn" onClick={() => setEditing(null)}>關閉</button></div><form action={saveMember}>{editing !== "new" && <input type="hidden" name="id" value={editing.id}/>}<div className="field"><label>會員姓名</label><input name="name" defaultValue={editing === "new" ? "" : editing.name} required maxLength={80}/></div><div className="field"><label>電話</label><input name="phone" type="tel" defaultValue={editing === "new" ? "" : editing.phone} placeholder="例如：0912-345-678"/></div><div className="field"><label>Email（選填）</label><input name="email" type="email" defaultValue={editing === "new" ? "" : editing.email}/></div><div className="form-actions"><button type="button" className="btn" onClick={() => setEditing(null)}>取消</button><button className="btn primary">儲存會員</button></div></form></section></div>}
    {pointMember && <div className="modal-backdrop"><section className="modal-card member-modal" role="dialog" aria-modal="true"><div className="panel-head"><div><h3>調整 {pointMember.name} 的點數</h3><p>目前 {pointMember.points} 點；加點填正數，扣點填負數。</p></div><button className="btn" onClick={() => setPointMember(null)}>關閉</button></div><form action={adjustPoints}><input type="hidden" name="customerId" value={pointMember.id}/><div className="field"><label>調整點數</label><input name="delta" type="number" step="1" placeholder="例如：10 或 -10" required/></div><div className="field"><label>調整原因（必填）</label><input name="note" maxLength={120} placeholder="例如：活動贈點、修正誤植" required/></div><div className="notice">人工調整會記錄操作者、時間、原因與調整後餘額。</div><div className="form-actions"><button type="button" className="btn" onClick={() => setPointMember(null)}>取消</button><button className="btn primary">確認調整</button></div></form></section></div>}
  </>;
}
