"use client";

import { useState } from "react";
import { createStaffAccount, resetStaffPassword, updateStaffAccess } from "@/app/(dashboard)/settings/actions";

export type StaffRow = { userId: string; displayName: string; email: string; role: string; active: boolean; isCurrent: boolean };
const roleName: Record<string,string> = { owner:"店主",manager:"店長",cashier:"收銀員",stock_clerk:"庫存人員" };

export function StaffManager({ rows }: { rows: StaffRow[] }) {
 const[creating,setCreating]=useState(false);const[resetting,setResetting]=useState<StaffRow|null>(null);
 return <section className="panel staff-panel"><div className="panel-head"><div><h3>員工帳號與權限</h3><p>每位員工使用自己的 Email 與密碼登入，不共用店主帳號。</p></div><button className="btn primary" onClick={()=>setCreating(true)}>＋ 建立員工帳號</button></div><div className="role-guide"><span><b>店長</b>營運、銷售、庫存與報表</span><span><b>收銀員</b>銷售、會員與退貨</span><span><b>庫存人員</b>商品、進貨與盤點</span></div><div className="table-wrap"><table><thead><tr><th>姓名／帳號</th><th>角色</th><th>狀態</th><th>權限設定</th><th>密碼</th></tr></thead><tbody>{rows.map((row)=><tr key={row.userId}><td><b>{row.displayName}</b>{row.isCurrent&&<span className="pill current-user">目前帳號</span>}<small className="staff-email">{row.email}</small></td><td><span className="pill">{roleName[row.role]||row.role}</span></td><td><span className={row.active?"pill":"pill low"}>{row.active?"可登入":"已停用"}</span></td><td>{row.role==="owner"?<span className="hint">店主完整權限</span>:<form className="staff-access-form" action={updateStaffAccess}><input type="hidden" name="userId" value={row.userId}/><select name="role" defaultValue={row.role}><option value="manager">店長</option><option value="cashier">收銀員</option><option value="stock_clerk">庫存人員</option></select><select name="active" defaultValue={String(row.active)}><option value="true">啟用</option><option value="false">停用</option></select><button className="btn sm">儲存</button></form>}</td><td>{row.role==="owner"?<span className="hint">請用「修改我的密碼」</span>:<button className="btn sm" onClick={()=>setResetting(row)}>重設密碼</button>}</td></tr>)}</tbody></table></div>
 {creating&&<div className="modal-backdrop"><section className="modal-card staff-modal" role="dialog" aria-modal="true"><div className="panel-head"><div><h3>建立員工登入帳號</h3><p>建立後可立即用 Email 與初始密碼登入。</p></div><button className="btn" onClick={()=>setCreating(false)}>關閉</button></div><form action={createStaffAccount}><div className="field"><label>員工顯示名稱</label><input name="displayName" maxLength={40} placeholder="例如：陳小美" required/></div><div className="field"><label>登入 Email</label><input name="email" type="email" autoComplete="off" placeholder="staff@example.com" required/></div><div className="form-grid"><div className="field"><label>初始密碼</label><input name="password" type="password" minLength={8} autoComplete="new-password" placeholder="至少 8 個字元" required/></div><div className="field"><label>再次輸入密碼</label><input name="confirm" type="password" minLength={8} autoComplete="new-password" required/></div></div><div className="field"><label>角色</label><select name="role" defaultValue="cashier"><option value="manager">店長</option><option value="cashier">收銀員</option><option value="stock_clerk">庫存人員</option></select></div><div className="notice">系統不會儲存或再次顯示這個密碼。請私下交給員工，並請員工登入後立即修改。</div><div className="form-actions"><button type="button" className="btn" onClick={()=>setCreating(false)}>取消</button><button className="btn primary">建立帳號</button></div></form></section></div>}
 {resetting&&<div className="modal-backdrop"><section className="modal-card staff-modal" role="dialog" aria-modal="true"><div className="panel-head"><div><h3>重設 {resetting.displayName} 的密碼</h3><p>{resetting.email}</p></div><button className="btn" onClick={()=>setResetting(null)}>關閉</button></div><form action={resetStaffPassword}><input type="hidden" name="userId" value={resetting.userId}/><div className="form-grid"><div className="field"><label>新密碼</label><input name="password" type="password" minLength={8} autoComplete="new-password" placeholder="至少 8 個字元" required/></div><div className="field"><label>再次輸入密碼</label><input name="confirm" type="password" minLength={8} autoComplete="new-password" required/></div></div><div className="notice">重設後舊密碼將無法再使用；新密碼不會保存在 ERP 資料表。</div><div className="form-actions"><button type="button" className="btn" onClick={()=>setResetting(null)}>取消</button><button className="btn primary">確認重設密碼</button></div></form></section></div>}
 </section>;
}
