"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

function back(message:string):never{redirect(`/shifts?message=${encodeURIComponent(message)}`)}
async function context(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:member}=await supabase.from("store_members").select("store_id,role").eq("user_id",user.id).eq("active",true).single();if(!member||!["owner","manager","cashier"].includes(member.role))back("您沒有交班盤點權限");return{supabase,member}}
export async function openShift(formData:FormData){const parsed=z.object({openingCash:z.coerce.number().min(0),note:z.string().trim().max(120)}).safeParse({openingCash:formData.get("openingCash"),note:String(formData.get("note")||"")});if(!parsed.success)back(parsed.error.issues[0]?.message||"開班資料錯誤");const{supabase,member}=await context();const{error}=await supabase.rpc("open_cash_shift",{p_store_id:member.store_id,p_opening_cash:parsed.data.openingCash,p_note:parsed.data.note});if(error)back("開班失敗："+error.message);revalidatePath("/shifts");back("開班完成，現在開始記錄本班交易");}
export async function addExpense(formData:FormData){const parsed=z.object({shiftId:z.string().uuid(),amount:z.coerce.number().positive(),note:z.string().trim().min(2).max(120)}).safeParse({shiftId:formData.get("shiftId"),amount:formData.get("amount"),note:formData.get("note")});if(!parsed.success)back(parsed.error.issues[0]?.message||"支出資料錯誤");const{supabase}=await context();const{error}=await supabase.rpc("add_cash_expense",{p_shift_id:parsed.data.shiftId,p_amount:parsed.data.amount,p_note:parsed.data.note});if(error)back("現金支出登記失敗："+error.message);revalidatePath("/shifts");back("現金支出已登記");}
export async function closeShift(formData:FormData){const parsed=z.object({shiftId:z.string().uuid(),actualCash:z.coerce.number().min(0),note:z.string().trim().max(120)}).safeParse({shiftId:formData.get("shiftId"),actualCash:formData.get("actualCash"),note:String(formData.get("note")||"")});if(!parsed.success)back(parsed.error.issues[0]?.message||"結班資料錯誤");const{supabase}=await context();const{data,error}=await supabase.rpc("close_cash_shift",{p_shift_id:parsed.data.shiftId,p_actual_cash:parsed.data.actualCash,p_note:parsed.data.note});if(error)back("結班失敗："+error.message);const result=data as{cash_difference?:number}|null;revalidatePath("/shifts");revalidatePath("/reports");back(`結班完成，現金差異 NT$${Number(result?.cash_difference||0).toLocaleString("zh-TW")}`);}
