import { PageHead } from "@/components/page-head";
import { SubmitButton } from "@/components/submit-button";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { addExpense, closeShift, openShift } from "./actions";

const money=(n:number)=>new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0}).format(n);
const dateTime=(value:string)=>new Intl.DateTimeFormat("zh-TW",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Taipei"}).format(new Date(value));
type Summary={shift:{id:string;opening_cash:number;opened_at:string};cash_sales:number;card_sales:number;transfer_sales:number;line_transfer_sales:number;cash_refunds:number;cash_expenses:number;expected_cash:number};

export default async function ShiftsPage({searchParams}:{searchParams:Promise<{message?:string}>}){
  const{message}=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();const{data:member}=await supabase.from("store_members").select("store_id,role").eq("user_id",user!.id).eq("active",true).single();
  if(!member||!["owner","manager","cashier"].includes(member.role))redirect("/overview");
  const[{data:open},{data:history}]=await Promise.all([supabase.from("cash_shifts").select("id,opening_cash,opened_at,opening_note,opened_by").eq("store_id",member!.store_id).eq("status","open").maybeSingle(),supabase.from("cash_shifts").select("id,opened_at,closed_at,opening_cash,cash_sales,transfer_sales,line_transfer_sales,cash_expenses,expected_cash,closing_cash,cash_difference").eq("store_id",member!.store_id).eq("status","closed").order("closed_at",{ascending:false}).limit(20)]);
  const{data:summaryData}=open?await supabase.rpc("get_cash_shift_summary",{p_shift_id:open.id}):{data:null};const summary=summaryData as Summary|null;
  const{data:expenses}=open?await supabase.from("cash_shift_expenses").select("id,amount,note,created_at").eq("shift_id",open.id).order("created_at",{ascending:false}):{data:[]};
  return <><PageHead title="交班與現金盤點" description="開班現金、收款、支出、結班實際現金與差異都留存紀錄"/>{message&&<div className="notice page-notice">{message}</div>}{!open?<section className="panel shift-open"><div className="panel-head"><div><h3>開始新班次</h3><p>開班後，銷售與退款會依付款方式自動歸入本班。</p></div></div><form action={openShift}><div className="form-grid"><div className="field"><label>開班現金</label><input name="openingCash" type="number" min="0" step="1" defaultValue="0" required/></div><div className="field"><label>開班備註</label><input name="note" maxLength={120} placeholder="例如：早班／備用金已點收"/></div></div><SubmitButton pendingLabel="開班處理中…">確認開班</SubmitButton></form></section>:<><section className="cards shift-cards"><div className="metric"><div className="metric-label">開班現金</div><div className="metric-value">{money(Number(summary?.shift.opening_cash||open.opening_cash))}</div><div className="metric-note">{dateTime(open.opened_at)}</div></div><div className="metric"><div className="metric-label">現金收入</div><div className="metric-value">{money(Number(summary?.cash_sales||0))}</div><div className="metric-note">現金退款 −{money(Number(summary?.cash_refunds||0))}</div></div><div className="metric"><div className="metric-label">轉帳收入</div><div className="metric-value">{money(Number(summary?.transfer_sales||0)+Number(summary?.line_transfer_sales||0))}</div><div className="metric-note">銀行 {money(Number(summary?.transfer_sales||0))}・LINE {money(Number(summary?.line_transfer_sales||0))}</div></div><div className="metric"><div className="metric-label">預期現金</div><div className="metric-value">{money(Number(summary?.expected_cash||0))}</div><div className="metric-note">支出 −{money(Number(summary?.cash_expenses||0))}</div></div></section><div className="grid-2"><section className="panel"><div className="panel-head"><div><h3>登記現金支出</h3><p>零用金、運費、臨時採買等</p></div></div><form action={addExpense}><input type="hidden" name="shiftId" value={open.id}/><div className="field"><label>支出金額</label><input name="amount" type="number" min="1" step="1" required/></div><div className="field"><label>支出原因</label><input name="note" minLength={2} maxLength={120} required/></div><SubmitButton pendingLabel="支出登記中…">登記支出</SubmitButton></form>{expenses?.length?<div className="shift-expenses">{expenses.map(expense=><div key={expense.id}><span>{dateTime(expense.created_at)}・{expense.note}</span><b>−{money(Number(expense.amount))}</b></div>)}</div>:null}</section><section className="panel"><div className="panel-head"><div><h3>結班現金盤點</h3><p>輸入錢櫃實際現金，系統自動計算差異。</p></div></div><form action={closeShift}><input type="hidden" name="shiftId" value={open.id}/><div className="field"><label>結班實際現金</label><input name="actualCash" type="number" min="0" step="1" required/></div><div className="field"><label>結班備註</label><input name="note" maxLength={120} placeholder="若有差異請說明"/></div><SubmitButton pendingLabel="結班計算中…">確認結班</SubmitButton></form></section></div></>}
  <section className="panel"><div className="panel-head"><div><h3>最近結班紀錄</h3><p>現金差異會永久保留</p></div></div><div className="table-wrap"><table><thead><tr><th>班次</th><th className="num">開班</th><th className="num">現金收入</th><th className="num">轉帳</th><th className="num">支出</th><th className="num">預期／實際</th><th className="num">差異</th></tr></thead><tbody>{!history?.length?<tr><td colSpan={7} className="empty">尚無結班紀錄</td></tr>:history.map(row=><tr key={row.id}><td>{dateTime(row.opened_at)}<small className="block-muted">至 {row.closed_at?dateTime(row.closed_at):"—"}</small></td><td className="num">{money(Number(row.opening_cash))}</td><td className="num">{money(Number(row.cash_sales))}</td><td className="num">{money(Number(row.transfer_sales)+Number(row.line_transfer_sales))}</td><td className="num">{money(Number(row.cash_expenses))}</td><td className="num">{money(Number(row.expected_cash))}／{money(Number(row.closing_cash))}</td><td className={`num ${Number(row.cash_difference)===0?"":"difference"}`}>{money(Number(row.cash_difference))}</td></tr>)}</tbody></table></div></section></>;
}
